window.SAMPLE_REQUIREMENTS = [
  {id:1, planYear:2026,title:'Enterprise software renewal',description:'Renewal of collaboration and productivity software subscriptions',department:'it',segment:'software',estimatedValue:240000,currency:'USD',needByDate:'2026-09-15',criticality:'high',buyingChannel:'negotiations',supplier:'Current enterprise software provider'},
  {id:2, planYear:2026,title:'Network equipment refresh',description:'Replacement of end-of-life switching and wireless equipment',department:'it',segment:'equipment',estimatedValue:180000,currency:'USD',needByDate:'2026-12-15',criticality:'high',buyingChannel:'publicRfp',supplier:''},
  {id:3, planYear:2026,title:'Leadership development programme',description:'External leadership development programme for senior managers',department:'hr',segment:'training',estimatedValue:65000,currency:'USD',needByDate:'2026-11-20',criticality:'medium',buyingChannel:'rfq',supplier:''},
  {id:4, planYear:2026,title:'Facilities maintenance contract',description:'Annual preventive and corrective maintenance services',department:'facilities',segment:'facilities',estimatedValue:320000,currency:'USD',needByDate:'2027-01-15',criticality:'high',buyingChannel:'publicRfp',supplier:'Current FM provider'},
  {id:5, planYear:2026,title:'Brand campaign support',description:'Creative and media-buying services for the annual brand campaign',department:'marketing',segment:'marketing',estimatedValue:95000,currency:'USD',needByDate:'2026-10-30',criticality:'medium',buyingChannel:'closed',supplier:''},
  {id:6, planYear:2026,title:'Tax advisory services',description:'Corporate tax advisory and compliance support',department:'finance',segment:'consulting',estimatedValue:48000,currency:'USD',needByDate:'2026-09-10',criticality:'medium',buyingChannel:'rfq',supplier:'Current tax adviser'},
  {id:7, planYear:2026,title:'Telecom services renewal',description:'Mobile and data connectivity services renewal',department:'operations',segment:'telecom',estimatedValue:145000,currency:'USD',needByDate:'2026-12-01',criticality:'high',buyingChannel:'negotiations',supplier:'Current telecom provider'},
  {id:8, planYear:2026,title:'Legal panel services',description:'External legal counsel panel for commercial and employment matters',department:'legal',segment:'legal',estimatedValue:110000,currency:'USD',needByDate:'2027-02-01',criticality:'medium',buyingChannel:'framework',supplier:''},
  {id:9, planYear:2026,title:'Process improvement consulting',description:'Operational process redesign and workflow optimisation support',department:'operations',segment:'consulting',estimatedValue:130000,currency:'USD',needByDate:'2026-11-01',criticality:'medium',buyingChannel:'closed',supplier:''},
  {id:10, planYear:2026,title:'Emergency generator repair',description:'Urgent specialist repair and replacement parts',department:'facilities',segment:'facilities',estimatedValue:22000,currency:'USD',needByDate:'2026-08-25',criticality:'high',buyingChannel:'emergency',supplier:'OEM service partner'}
];
