window.SAMPLE_REQUIREMENTS = [
  {
    "id": 1,
    "planYear": 2027,
    "title": "Employee Medical Insurance",
    "description": "Annual employee medical insurance",
    "department": "hr",
    "segment": "healthcareServices",
    "estimatedValue": 18230000,
    "currency": "AED",
    "needByDate": "2027-01-10",
    "criticality": "urgent",
    "buyingChannel": "framework",
    "supplier": "Cigna"
  },
  {
    "id": 2,
    "planYear": 2027,
    "title": "Litigation Support",
    "description": "External litigation support services",
    "department": "legal",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1755871,
    "currency": "AED",
    "needByDate": "2027-05-21",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "Al Tamimi"
  },
  {
    "id": 3,
    "planYear": 2027,
    "title": "Building Maintenance",
    "description": "Routine facilities maintenance",
    "department": "facilities",
    "segment": "buildingAndFacilityConstructionAndMaintenanceServices",
    "estimatedValue": 2378888,
    "currency": "AED",
    "needByDate": "2027-05-11",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 4,
    "planYear": 2027,
    "title": "Cybersecurity Assessment",
    "description": "Enterprise cybersecurity assessment",
    "department": "it",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1520929,
    "currency": "EUR",
    "needByDate": "2027-07-09",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 5,
    "planYear": 2027,
    "title": "Substation ABC",
    "description": "EPC project for a new ABC substation",
    "department": "projects",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 127000000,
    "currency": "AED",
    "needByDate": "2027-01-19",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 6,
    "planYear": 2027,
    "title": "CRM Support Renewal",
    "description": "CRM platform support renewal",
    "department": "customerService",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1181328,
    "currency": "AED",
    "needByDate": "2027-05-22",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 7,
    "planYear": 2027,
    "title": "Tax Consulting Services",
    "description": "Corporate tax consulting support",
    "department": "finance",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 5308802,
    "currency": "AED",
    "needByDate": "2027-07-22",
    "criticality": "regular",
    "buyingChannel": "framework",
    "supplier": "EY"
  },
  {
    "id": 8,
    "planYear": 2027,
    "title": "Recruitment Services",
    "description": "External recruitment support",
    "department": "hr",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 22518000,
    "currency": "AED",
    "needByDate": "2027-01-10",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "TASC"
  },
  {
    "id": 9,
    "planYear": 2027,
    "title": "E-Sourcing Platform Renewal",
    "description": "Renewal of procurement platform",
    "department": "supplyChain",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 4323160,
    "currency": "AED",
    "needByDate": "2027-10-30",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "SAP"
  },
  {
    "id": 10,
    "planYear": 2027,
    "title": "Property Insurance",
    "description": "Annual property insurance",
    "department": "finance",
    "segment": "financialInstrumentsProductsContractsAndAgreements",
    "estimatedValue": 1213782,
    "currency": "AED",
    "needByDate": "2027-04-20",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 11,
    "planYear": 2027,
    "title": "Transformer Maintenance",
    "description": "Preventive transformer maintenance",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1869881,
    "currency": "AED",
    "needByDate": "2027-11-30",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "AG Power"
  },
  {
    "id": 12,
    "planYear": 2027,
    "title": "XYZ Pumping Station",
    "description": "EPC contract for a new XYZ pumping station",
    "department": "projects",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 214768000,
    "currency": "AED",
    "needByDate": "2027-07-14",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 13,
    "planYear": 2027,
    "title": "Office Cleaning Services",
    "description": "Routine office cleaning services",
    "department": "facilities",
    "segment": "industrialCleaningServices",
    "estimatedValue": 3137497,
    "currency": "AED",
    "needByDate": "2027-06-11",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 14,
    "planYear": 2027,
    "title": "CRM Support Renewal",
    "description": "CRM platform support renewal",
    "department": "customerService",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1230572,
    "currency": "AED",
    "needByDate": "2027-03-24",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Salesforce"
  },
  {
    "id": 15,
    "planYear": 2027,
    "title": "Financial Reporting Software",
    "description": "Financial reporting software renewal",
    "department": "finance",
    "segment": "informationTechnologyBroadcastingAndTelecommunications",
    "estimatedValue": 564672,
    "currency": "AED",
    "needByDate": "2027-03-30",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 16,
    "planYear": 2027,
    "title": "Power Cable Supply",
    "description": "Supply of medium-voltage power cables",
    "department": "projects",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 6345000,
    "currency": "AED",
    "needByDate": "2027-04-04",
    "criticality": "regular",
    "buyingChannel": "framework",
    "supplier": "AG Power"
  },
  {
    "id": 17,
    "planYear": 2027,
    "title": "CRM Support Renewal",
    "description": "GIS platform support renewal",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1538812,
    "currency": "AED",
    "needByDate": "2027-05-11",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "GIS International"
  },
  {
    "id": 18,
    "planYear": 2027,
    "title": "Cable Installation Works",
    "description": "Installation of power cables",
    "department": "projects",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 12706743,
    "currency": "AED",
    "needByDate": "2027-03-15",
    "criticality": "regular",
    "buyingChannel": "framework",
    "supplier": "Local Contractor LLC"
  },
  {
    "id": 19,
    "planYear": 2027,
    "title": "Legal Advisory Services",
    "description": "External legal consulting support",
    "department": "legal",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 8413782,
    "currency": "AED",
    "needByDate": "2027-08-31",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Al Tamimi"
  },
  {
    "id": 20,
    "planYear": 2027,
    "title": "Warehouse Renovation",
    "description": "Warehouse Renovation",
    "department": "supplyChain",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 2751948,
    "currency": "AED",
    "needByDate": "2027-06-09",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "Local Contractor LLC"
  },
  {
    "id": 21,
    "planYear": 2027,
    "title": "Building Maintenance",
    "description": "Routine facilities maintenance",
    "department": "facilities",
    "segment": "buildingAndFacilityConstructionAndMaintenanceServices",
    "estimatedValue": 161001000,
    "currency": "AED",
    "needByDate": "2027-12-09",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 22,
    "planYear": 2027,
    "title": "Fleet Maintenance",
    "description": "Maintenance of company vehicles",
    "department": "facilities",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 2478090,
    "currency": "AED",
    "needByDate": "2027-02-26",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "Toyota"
  },
  {
    "id": 23,
    "planYear": 2027,
    "title": "Primavera Platform Renewal",
    "description": "Renewal of Primavera project management licenses",
    "department": "projects",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 918911,
    "currency": "EUR",
    "needByDate": "2027-05-16",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Primavera Middle East"
  },
  {
    "id": 24,
    "planYear": 2027,
    "title": "Board Advisory Services",
    "description": "External Board consulting support",
    "department": "ceoOffice",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 6520905,
    "currency": "AED",
    "needByDate": "2027-04-01",
    "criticality": "urgent",
    "buyingChannel": "currentContract",
    "supplier": "BCG"
  },
  {
    "id": 25,
    "planYear": 2027,
    "title": "Training Services",
    "description": "Corporate training programs",
    "department": "ceoOffice",
    "segment": "educationAndTrainingServices",
    "estimatedValue": 984935,
    "currency": "AED",
    "needByDate": "2027-07-17",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Kearney"
  },
  {
    "id": 26,
    "planYear": 2027,
    "title": "SCADA Support",
    "description": "Operational SCADA support services",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1642143,
    "currency": "AED",
    "needByDate": "2027-03-16",
    "criticality": "urgent",
    "buyingChannel": "rfq",
    "supplier": ""
  },
  {
    "id": 27,
    "planYear": 2027,
    "title": "Call Center Support",
    "description": "Customer support outsourcing",
    "department": "customerService",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1947949,
    "currency": "AED",
    "needByDate": "2027-02-28",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "Etisalat"
  },
  {
    "id": 28,
    "planYear": 2027,
    "title": "Supplier Due Diligence Services",
    "description": "Supplier screening services",
    "department": "supplyChain",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 803727,
    "currency": "AED",
    "needByDate": "2027-09-25",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 29,
    "planYear": 2027,
    "title": "Generator Spare Parts",
    "description": "Supply of generator spare parts",
    "department": "oAndM",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 1301498,
    "currency": "EUR",
    "needByDate": "2027-08-09",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 30,
    "planYear": 2027,
    "title": "Office Supplies",
    "description": "Office Supplies",
    "department": "customerService",
    "segment": "officeEquipmentAndAccessoriesAndSupplies",
    "estimatedValue": 443422,
    "currency": "AED",
    "needByDate": "2027-05-29",
    "criticality": "regular",
    "buyingChannel": "rfq",
    "supplier": ""
  },
  {
    "id": 31,
    "planYear": 2027,
    "title": "Staff Uniforms",
    "description": "Staff Uniforms",
    "department": "oAndM",
    "segment": "personalAndDomesticServices",
    "estimatedValue": 5900982,
    "currency": "AED",
    "needByDate": "2027-01-20",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "UnformCo Ltd."
  },
  {
    "id": 32,
    "planYear": 2027,
    "title": "HVAC Maintenance",
    "description": "Air conditioning maintenance services",
    "department": "facilities",
    "segment": "distributionAndConditioningSystemsAndEquipmentAndComponents",
    "estimatedValue": 1033224,
    "currency": "AED",
    "needByDate": "2027-01-19",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 33,
    "planYear": 2027,
    "title": "Fleet Maintenance",
    "description": "Maintenance of company vehicles",
    "department": "facilities",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 2250413,
    "currency": "AED",
    "needByDate": "2027-12-28",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 34,
    "planYear": 2027,
    "title": "CRM Support Renewal",
    "description": "CRM platform support renewal",
    "department": "customerService",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 2581207,
    "currency": "USD",
    "needByDate": "2027-09-30",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "HP"
  },
  {
    "id": 35,
    "planYear": 2027,
    "title": "ISO Certification",
    "description": "ISO Certification",
    "department": "ceoOffice",
    "segment": "organizationsAndClubs",
    "estimatedValue": 574993,
    "currency": "USD",
    "needByDate": "2027-01-19",
    "criticality": "urgent",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 36,
    "planYear": 2027,
    "title": "ERP Support Renewal",
    "description": "Annual ERP platform support renewal",
    "department": "it",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 866965,
    "currency": "AED",
    "needByDate": "2027-06-02",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": ""
  },
  {
    "id": 37,
    "planYear": 2027,
    "title": "Recruitment Services",
    "description": "External recruitment support",
    "department": "hr",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 3137798,
    "currency": "AED",
    "needByDate": "2027-06-23",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Page Executive"
  },
  {
    "id": 38,
    "planYear": 2027,
    "title": "Employee Satisfaction Surbey",
    "description": "Annual employee satisfaction survey",
    "department": "hr",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 924269,
    "currency": "EUR",
    "needByDate": "2027-06-29",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Andersen"
  },
  {
    "id": 39,
    "planYear": 2027,
    "title": "Project Support Services",
    "description": "Project support services framework",
    "department": "projects",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 42196000,
    "currency": "AED",
    "needByDate": "2027-01-10",
    "criticality": "regular",
    "buyingChannel": "rfq",
    "supplier": ""
  },
  {
    "id": 40,
    "planYear": 2027,
    "title": "Fuel Supply",
    "description": "Supply of diesel and petrol",
    "department": "supplyChain",
    "segment": "fuelsAndFuelAdditivesAndLubricantsAndAntiCorrosiveMaterials",
    "estimatedValue": 4130291,
    "currency": "AED",
    "needByDate": "2027-04-13",
    "criticality": "regular",
    "buyingChannel": "eauction",
    "supplier": ""
  },
  {
    "id": 41,
    "planYear": 2027,
    "title": "CRM Support Renewal",
    "description": "GIS platform support renewal",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 885574,
    "currency": "GBP",
    "needByDate": "2027-06-23",
    "criticality": "urgent",
    "buyingChannel": "extension20",
    "supplier": "Etisalat"
  },
  {
    "id": 42,
    "planYear": 2027,
    "title": "Training Services",
    "description": "Corporate training programs",
    "department": "hr",
    "segment": "educationAndTrainingServices",
    "estimatedValue": 644356,
    "currency": "EUR",
    "needByDate": "2027-10-30",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 43,
    "planYear": 2027,
    "title": "HVAC Maintenance",
    "description": "Air conditioning maintenance services",
    "department": "facilities",
    "segment": "distributionAndConditioningSystemsAndEquipmentAndComponents",
    "estimatedValue": 3480404,
    "currency": "AED",
    "needByDate": "2027-08-11",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Mitsubishi"
  },
  {
    "id": 44,
    "planYear": 2027,
    "title": "Supplier Due Diligence Services",
    "description": "D&B subscription",
    "department": "supplyChain",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 32866,
    "currency": "EUR",
    "needByDate": "2027-10-20",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "D&B"
  },
  {
    "id": 45,
    "planYear": 2027,
    "title": "Legal Advisory Services",
    "description": "External legal consulting support",
    "department": "legal",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 266705,
    "currency": "AED",
    "needByDate": "2027-11-24",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 46,
    "planYear": 2027,
    "title": "Call Center Support",
    "description": "Customer support outsourcing",
    "department": "customerService",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 730418,
    "currency": "GBP",
    "needByDate": "2027-01-07",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "Cisco"
  },
  {
    "id": 47,
    "planYear": 2027,
    "title": "Fleet Maintenance",
    "description": "Maintenance of company vehicles",
    "department": "facilities",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 906482,
    "currency": "AED",
    "needByDate": "2027-05-24",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "HP"
  },
  {
    "id": 48,
    "planYear": 2027,
    "title": "Audit Advisory Services",
    "description": "External financial audit advisory",
    "department": "finance",
    "segment": "financialInstrumentsProductsContractsAndAgreements",
    "estimatedValue": 152566,
    "currency": "USD",
    "needByDate": "2027-09-06",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 49,
    "planYear": 2027,
    "title": "Network Planning Support",
    "description": "Consultancy for the Netork Planning",
    "department": "projects",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 2465958,
    "currency": "USD",
    "needByDate": "2027-12-30",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 50,
    "planYear": 2027,
    "title": "Great Place to Work",
    "description": "Great Place to Work assessment and awards",
    "department": "hr",
    "segment": "organizationsAndClubs",
    "estimatedValue": 713240,
    "currency": "EUR",
    "needByDate": "2027-05-17",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Andersen"
  },
  {
    "id": 51,
    "planYear": 2027,
    "title": "Warehouse Racking",
    "description": "Scrap storage infrastructure",
    "department": "supplyChain",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 490773,
    "currency": "AED",
    "needByDate": "2027-02-13",
    "criticality": "regular",
    "buyingChannel": "rfq",
    "supplier": ""
  },
  {
    "id": 52,
    "planYear": 2027,
    "title": "Call Center Support",
    "description": "Customer support outsourcing",
    "department": "customerService",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 2554553,
    "currency": "EUR",
    "needByDate": "2027-01-02",
    "criticality": "regular",
    "buyingChannel": "eauction",
    "supplier": ""
  },
  {
    "id": 53,
    "planYear": 2027,
    "title": "Chemicals",
    "description": "Chemical supplies",
    "department": "oAndM",
    "segment": "chemicalsIncludingBioChemicalsAndGasMaterials",
    "estimatedValue": 4405690,
    "currency": "AED",
    "needByDate": "2027-09-05",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 54,
    "planYear": 2027,
    "title": "Power Cable Supply",
    "description": "Supply of medium-voltage power cables",
    "department": "oAndM",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 3263903,
    "currency": "AED",
    "needByDate": "2027-01-31",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "HP"
  },
  {
    "id": 55,
    "planYear": 2027,
    "title": "Employee Medical Insurance",
    "description": "Employee of the Month ",
    "department": "hr",
    "segment": "employeeOfTheMonthEventsAndAwards",
    "estimatedValue": 1382723,
    "currency": "AED",
    "needByDate": "2027-09-28",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Andersen"
  },
  {
    "id": 56,
    "planYear": 2027,
    "title": "E-Sourcing Platform Renewal",
    "description": "Cloud services for S4/HANA ERP",
    "department": "it",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 2130677,
    "currency": "AED",
    "needByDate": "2027-06-14",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 57,
    "planYear": 2027,
    "title": "FIDIC contract templates",
    "description": "Development of FIDIC contract templates",
    "department": "legal",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1484848,
    "currency": "AED",
    "needByDate": "2027-10-25",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Al Tamimi"
  },
  {
    "id": 58,
    "planYear": 2027,
    "title": "Cybersecurity Awareness Campaign",
    "description": "Preparation and Execution of Cybersecurity Awareness Campaign",
    "department": "it",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 833034,
    "currency": "AED",
    "needByDate": "2027-04-15",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 59,
    "planYear": 2027,
    "title": "Building Maintenance",
    "description": "Routine facilities maintenance",
    "department": "facilities",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 0,
    "currency": "AED",
    "needByDate": "2027-05-04",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 60,
    "planYear": 2027,
    "title": "Pumping Station ABC",
    "description": "EPC project for the pumping station ABC",
    "department": "projects",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 295606700,
    "currency": "AED",
    "needByDate": "2027-04-23",
    "criticality": "urgent",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 61,
    "planYear": 2027,
    "title": "Billing Support Renewal",
    "description": "Billing platform support renewal",
    "department": "it",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 391441,
    "currency": "EUR",
    "needByDate": "2027-10-05",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Amdocs"
  },
  {
    "id": 62,
    "planYear": 2027,
    "title": "New pipeline in Eastern Region",
    "description": "EPC project for the costruction of a new pipeline in Eastern Region",
    "department": "projects",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 322580403,
    "currency": "AED",
    "needByDate": "2027-07-18",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "Local Contractor LLC"
  },
  {
    "id": 63,
    "planYear": 2027,
    "title": "Drinking Water Supply",
    "description": "Supply of drinking water for offices",
    "department": "supplyChain",
    "segment": "personalAndDomesticServices",
    "estimatedValue": 1951521,
    "currency": "AED",
    "needByDate": "2027-10-01",
    "criticality": "regular",
    "buyingChannel": "eauction",
    "supplier": ""
  },
  {
    "id": 64,
    "planYear": 2027,
    "title": "Tax Consulting Services",
    "description": "UK corporate tax consulting support",
    "department": "finance",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 868751,
    "currency": "GBP",
    "needByDate": "2027-03-21",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 65,
    "planYear": 2027,
    "title": "Training Services",
    "description": "Corporate training programs",
    "department": "hr",
    "segment": "educationAndTrainingServices",
    "estimatedValue": 0,
    "currency": "AED",
    "needByDate": "2027-01-13",
    "criticality": "regular",
    "buyingChannel": "framework",
    "supplier": "Dell"
  },
  {
    "id": 66,
    "planYear": 2027,
    "title": "Call Center Support",
    "description": "Supply of motor oils",
    "department": "customerService",
    "segment": "commercialAndMilitaryAndPrivateVehiclesAndTheirAccessoriesAndComponents",
    "estimatedValue": 2511977,
    "currency": "AED",
    "needByDate": "2027-03-17",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 67,
    "planYear": 2027,
    "title": "Cable Installation Works",
    "description": "Installation of power cables",
    "department": "projects",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 66486900,
    "currency": "AED",
    "needByDate": "2027-08-19",
    "criticality": "urgent",
    "buyingChannel": "currentContract",
    "supplier": "Oracle"
  },
  {
    "id": 68,
    "planYear": 2027,
    "title": "Telecommunication Services",
    "description": "Fixed and mobile telecom services",
    "department": "it",
    "segment": "informationTechnologyBroadcastingAndTelecommunications",
    "estimatedValue": 51821136,
    "currency": "AED",
    "needByDate": "2027-02-13",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Etisalat"
  },
  {
    "id": 69,
    "planYear": 2027,
    "title": "Smart Metering Support",
    "description": "Operational smart metering support services",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 4272211,
    "currency": "AED",
    "needByDate": "2027-07-01",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": ""
  },
  {
    "id": 70,
    "planYear": 2027,
    "title": "Corporate Reporting Consulting Services",
    "description": "Corporate reporting support",
    "department": "finance",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 2192959,
    "currency": "AED",
    "needByDate": "2027-01-19",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "EY"
  },
  {
    "id": 71,
    "planYear": 2027,
    "title": "Pumping Spare Parts",
    "description": "Supply of pumping spare parts",
    "department": "oAndM",
    "segment": "distributionAndConditioningSystemsAndEquipmentAndComponents",
    "estimatedValue": 6034949,
    "currency": "AED",
    "needByDate": "2027-07-15",
    "criticality": "emergency",
    "buyingChannel": "eauction",
    "supplier": ""
  },
  {
    "id": 72,
    "planYear": 2027,
    "title": "Customer satisfaction",
    "description": "Customer satisfaction survey",
    "department": "customerService",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 268542,
    "currency": "AED",
    "needByDate": "2027-06-19",
    "criticality": "regular",
    "buyingChannel": "rfq",
    "supplier": ""
  },
  {
    "id": 73,
    "planYear": 2027,
    "title": "Office Cleaning Services",
    "description": "Routine office cleaning services",
    "department": "facilities",
    "segment": "industrialCleaningServices",
    "estimatedValue": 1090934,
    "currency": "USD",
    "needByDate": "2027-12-30",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "HP"
  },
  {
    "id": 74,
    "planYear": 2027,
    "title": "M&A Due Diligence Services",
    "description": "Due diligence services",
    "department": "ceoOffice",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 2134776,
    "currency": "USD",
    "needByDate": "2027-04-02",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "Kearney"
  },
  {
    "id": 75,
    "planYear": 2027,
    "title": "NMS Center Upgrade",
    "description": "Upgrade of the Network Management Center",
    "department": "projects",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 3362787,
    "currency": "USD",
    "needByDate": "2027-07-20",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": ""
  },
  {
    "id": 76,
    "planYear": 2027,
    "title": "Substation DEF - Phase 2",
    "description": "Next stage of substation DEF expansion",
    "department": "projects",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 65000000,
    "currency": "AED",
    "needByDate": "2027-11-15",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Local Contractor LLC"
  },
  {
    "id": 77,
    "planYear": 2027,
    "title": "Civil Works",
    "description": "Minor civil construction works",
    "department": "projects",
    "segment": "structuresAndBuildingAndConstructionAndManufacturingComponentsAndSupplies",
    "estimatedValue": 2115137,
    "currency": "AED",
    "needByDate": "2027-12-09",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 78,
    "planYear": 2027,
    "title": "Membranes",
    "description": "Supply of mebranes",
    "department": "oAndM",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 2498337,
    "currency": "EUR",
    "needByDate": "2027-11-27",
    "criticality": "emergency",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 79,
    "planYear": 2027,
    "title": "Communal Charges",
    "description": "Communal charges for main office",
    "department": "facilities",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 2440878,
    "currency": "AED",
    "needByDate": "2027-03-14",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "EWEC"
  },
  {
    "id": 80,
    "planYear": 2027,
    "title": "Distribution transformers",
    "description": "Distribution transformers",
    "department": "projects",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 73143000,
    "currency": "AED",
    "needByDate": "2027-08-22",
    "criticality": "urgent",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 81,
    "planYear": 2027,
    "title": "Generator Spare Parts",
    "description": "Supply of generator spare parts",
    "department": "oAndM",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 3026029,
    "currency": "USD",
    "needByDate": "2027-02-28",
    "criticality": "regular",
    "buyingChannel": "single",
    "supplier": "Schneider Electric"
  },
  {
    "id": 82,
    "planYear": 2027,
    "title": "Pest control",
    "description": "Pest control services for HQ",
    "department": "facilities",
    "segment": "buildingAndFacilityConstructionAndMaintenanceServices",
    "estimatedValue": 604292,
    "currency": "AED",
    "needByDate": "2027-09-08",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": ""
  },
  {
    "id": 83,
    "planYear": 2027,
    "title": "Travel and Lodging",
    "description": "Travel and Lodging in Germany",
    "department": "hr",
    "segment": "travelAndFoodAndLodgingAndEntertainmentServices",
    "estimatedValue": 157560,
    "currency": "EUR",
    "needByDate": "2027-02-11",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "TravelCo LLC"
  },
  {
    "id": 84,
    "planYear": 2027,
    "title": "Executive vehicle leasing",
    "description": "Executive vehicle leasing",
    "department": "ceoOffice",
    "segment": "transportationAndStorageAndMailServices",
    "estimatedValue": 1532604,
    "currency": "AED",
    "needByDate": "2027-01-23",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "TravelCo LLC"
  },
  {
    "id": 85,
    "planYear": 2027,
    "title": "Substation LMN Upgrade",
    "description": "Electrical substation LMN upgrade project",
    "department": "projects",
    "segment": "powerGenerationAndDistributionMachineryAndAccessories",
    "estimatedValue": 73246600,
    "currency": "AED",
    "needByDate": "2027-06-30",
    "criticality": "urgent",
    "buyingChannel": "negotiations",
    "supplier": "Local Contractor LLC"
  },
  {
    "id": 86,
    "planYear": 2027,
    "title": "Audit Advisory Services",
    "description": "External financial audit advisory",
    "department": "finance",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1940661,
    "currency": "AED",
    "needByDate": "2027-12-21",
    "criticality": "regular",
    "buyingChannel": "extension20",
    "supplier": "EY"
  },
  {
    "id": 87,
    "planYear": 2027,
    "title": "Laptop Replacement",
    "description": "Replacement of obsolete laptops",
    "department": "it",
    "segment": "informationTechnologyBroadcastingAndTelecommunications",
    "estimatedValue": 1327228,
    "currency": "AED",
    "needByDate": "2027-08-13",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "HP"
  },
  {
    "id": 88,
    "planYear": 2027,
    "title": "Financial Reporting Software",
    "description": "Financial reporting software renewal",
    "department": "finance",
    "segment": "informationTechnologyBroadcastingAndTelecommunications",
    "estimatedValue": 807186,
    "currency": "EUR",
    "needByDate": "2027-07-25",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "SAP"
  },
  {
    "id": 89,
    "planYear": 2027,
    "title": "Customer connections",
    "description": "Customer connections",
    "department": "oAndM",
    "segment": "publicUtilitiesAndPublicSectorRelatedServices",
    "estimatedValue": 43769903,
    "currency": "AED",
    "needByDate": "2027-10-27",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "Local Contractor LLC, EPC Co ltd."
  },
  {
    "id": 90,
    "planYear": 2027,
    "title": "Digital Strategy",
    "description": "Digital Strategy Development",
    "department": "ceoOffice",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1726487,
    "currency": "AED",
    "needByDate": "2027-08-22",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Kearney"
  },
  {
    "id": 91,
    "planYear": 2027,
    "title": "Infrastructure Repars",
    "description": "Infrastructure Repars & Maintenance",
    "department": "oAndM",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 177089000,
    "currency": "AED",
    "needByDate": "2027-05-29",
    "criticality": "urgent",
    "buyingChannel": "framework",
    "supplier": ""
  },
  {
    "id": 92,
    "planYear": 2027,
    "title": "Arbitration Support",
    "description": "Arbitration support services",
    "department": "legal",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 0,
    "currency": "AED",
    "needByDate": "2027-05-15",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "Al Tamimi"
  },
  {
    "id": 93,
    "planYear": 2027,
    "title": "API Orchestration Platform Renewal",
    "description": "API Orchestration Platform Renewal",
    "department": "it",
    "segment": "engineeringAndResearchAndTechnologyBasedServices",
    "estimatedValue": 1730510,
    "currency": "USD",
    "needByDate": "2027-10-09",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "SAP"
  },
  {
    "id": 94,
    "planYear": 2027,
    "title": "Front Desk Support",
    "description": "Front desk support outsourcing",
    "department": "customerService",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 16730000,
    "currency": "AED",
    "needByDate": "2027-01-24",
    "criticality": "regular",
    "buyingChannel": "publicRfp",
    "supplier": ""
  },
  {
    "id": 95,
    "planYear": 2027,
    "title": "Switchgear Spare Parts",
    "description": "Supply of switchgear spare parts",
    "department": "oAndM",
    "segment": "electricalSystemsAndLightingAndComponentsAndAccessoriesAndSupplies",
    "estimatedValue": 3227437,
    "currency": "EUR",
    "needByDate": "2027-11-22",
    "criticality": "regular",
    "buyingChannel": "currentContract",
    "supplier": "ABB"
  },
  {
    "id": 96,
    "planYear": 2027,
    "title": "Company Day",
    "description": "Company Day",
    "department": "ceoOffice",
    "segment": "travelAndFoodAndLodgingAndEntertainmentServices",
    "estimatedValue": 3220383,
    "currency": "AED",
    "needByDate": "2027-01-23",
    "criticality": "urgent",
    "buyingChannel": "negotiations",
    "supplier": "Andersen"
  },
  {
    "id": 97,
    "planYear": 2027,
    "title": "GIS Advisory Services",
    "description": "External GIS consulting support",
    "department": "oAndM",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 0,
    "currency": "AED",
    "needByDate": "2027-10-28",
    "criticality": "regular",
    "buyingChannel": "closed",
    "supplier": ""
  },
  {
    "id": 98,
    "planYear": 2027,
    "title": "Tax Consulting Services",
    "description": "Corporate tax consulting support",
    "department": "finance",
    "segment": "managementAndBusinessProfessionalsAndAdministrativeServices",
    "estimatedValue": 1258418,
    "currency": "AED",
    "needByDate": "2027-04-29",
    "criticality": "regular",
    "buyingChannel": "negotiations",
    "supplier": "EY"
  },
  {
    "id": 99,
    "planYear": 2027,
    "title": "Office Supplies",
    "description": "Routine office supplies and consumables",
    "department": "facilities",
    "segment": "officeEquipmentAndAccessoriesAndSupplies",
    "estimatedValue": 2551565,
    "currency": "AED",
    "needByDate": "2027-08-24",
    "criticality": "regular",
    "buyingChannel": "eauction",
    "supplier": ""
  }
];
